organization: asyncapi
defaultSticker: cm9sq1lb7148060cjmbvrpbcjh
stickers:
  - id: cm9sq1lb7148060cjmbvrpbcjh
    alias: contributor-badge
  - id: cm9sq9gav08040cl7wllo7t58
    alias: maintainer-badge
  - id: cm9sqfgt969010cjsedmcnnor
    alias: triager-badge
  - id: cm9sqidpx183630cjmkyo9jsi3
    alias: ambassador-badge
  - id: cm9sqoota86860cjslsvmyok6
    alias: leader-badge
  - id: cm9sqr74o209520cjmt9rksacd
    alias: speaker-badge
  - id: cm9sqsqag213480cjm3x8w3a4l
    alias: volunteer-badge
  - id: cm9squ4eq103310cjs0b6pjodo
    alias: mentor-badge
  - id: cm9sqpuco89820cjscmppqm99
    alias: champion-badge
 
 # more stickers

# To issue the badges tag @holopin-bot @username sticker-alias