name: 📑 Docs
description: Propose changes and improvements to AsyncAPI Docs.
labels: "📑 docs"
title: "[📑 Docs]: "
assignees: alequetzalli
  - 
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing to AsyncAPI Docs! 📑 👩🏻‍💻 We appreciate your feedback, ideas, and contributions. 
        
        Before filing this issue, please make sure to check if there's already a similar issue open in our [Dev Docs Board](https://github.com/orgs/asyncapi/projects/8).
  
  - type: textarea
    id: reason-context
    attributes:
      label: What Dev Docs changes are you proposing?
      description: Why do the Docs need this improvement? What is the motivation for this change? How will this change benefit our Open-Source community?
      placeholder: "I would like to contribute to AsyncAPI Docs 📑 by..."
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/asyncapi/.github/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
