# Composite action that can be used in other actions or workflows.
# It does not run on its own.
# Replacement for LoveToKnow/slackify-markdown-action.

name: 'Make Markdown Pretty in Slack'
description: Action used in multiple workflows to handle convertion from markdown to slack--specific-text
inputs:
  markdown:
    description: Markdown content
    required: true
outputs:
  text:
    description: Slack Markdown
    value: ${{ steps.slackify.outputs.text }}
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Create and initialize slackify directory
      shell: bash
      run: | # We need to create a directory to install the slackify-markdown package to avoid conflicting with repositories using pnpm.
        mkdir slackify
        cd slackify
        npm init -y
    - name: Install slackify-markdown package
      shell: bash
      working-directory: slackify
      run: |
        npm install slackify-markdown@4.3.1
    - name: Slackify
      uses: actions/github-script@v6
      id: slackify
      working-directory: slackify
      env:
        MARKDOWN: ${{ inputs.markdown }}
      with:
        script: |
          const slackifyMarkdown = require('slackify-markdown');

          try {
              const md = process.env.MARKDOWN;
              const mrkdwn = slackifyMarkdown(md);
              core.setOutput('text', mrkdwn);
          } catch (error) {
              core.setFailed(error.message);
          }
    - name: Clean up slackify directory
      shell: bash
      run: |
        rm -rf slackify
