#Composite action that can be used in other actions or workflows
#It do not run on its own
#Replacement for LoveToKnow/slackify-markdown-action

name: 'Make Markdown Pretty in Slack'
description: Action used in multiple workflows to handle convertion from markdown to slack--specific-text
inputs:
  markdown:
    description: Markdown content
    required: true
outputs:
  text:
    description: Markdown converted to Slack
    value: ${{ steps.slackify.outputs.text }}
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - name: Install slackify-markdown package
      shell: bash
      run: npm install slackify-markdown@4.3.1
    - name: Slackify
      uses: actions/github-script@v6
      id: slackify
      with:
        script: |
          const slackifyMarkdown = require('slackify-markdown');

          try {
              const md = `${{ inputs.markdown }}`;
              const mrkdwn = slackifyMarkdown(md);
              core.setOutput('text', mrkdwn);
          } catch (error) {
              core.setFailed(error.message);
          }