name: Emoji Checker

on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]

jobs:
  check-emojis:
    runs-on: ubuntu-latest
    steps:
      - name: Check emojis
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const query = `
              query($owner: String!, $name: String!, $cursor: String) {
                repository(owner: $owner, name: $name) {
                  issues(first: 100, after: $cursor) {
                    nodes {
                      title
                      url
                      reactions(first: 100) {
                        totalCount
                      }
                    }
                    pageInfo {
                      endCursor
                      hasNextPage
                    }
                  }
                  pullRequests(first: 100, after: $cursor) {
                    nodes {
                      title
                      url
                      reactions(first: 100) {
                        totalCount
                      }
                    }
                    pageInfo {
                      endCursor
                      hasNextPage
                    }
                  }
                }
              }
            `;
            const variables = { owner: context.repo.owner, name: context.repo.repo };
            let hasNextPage = true;
            let cursor = null;
            while (hasNextPage) {
              if (cursor) {
                variables.cursor = cursor;
              }
              const result = await github.graphql(query, variables);
              const issues = result.repository.issues.nodes;
              const pullRequests = result.repository.pullRequests.nodes;
              const nodes = issues.concat(pullRequests);
              for (const node of nodes) {
                const count = node.reactions.totalCount;
                if (count > 0) {
                  const title = node.title;
                  const url = node.url;
                  const message = `The issue/PR "${title}" (${url}) has ${count} emojis.`;
                  console.log(message);
                  //await slackBot.postMessage(message);
                }
              }
              cursor = issues.pageInfo.endCursor || pullRequests.pageInfo.endCursor;
              hasNextPage = issues.pageInfo.hasNextPage || pullRequests.pageInfo.hasNextPage;
            }
