#This workflow is centrally managed in https://github.com/asyncapi/.github/
#Don't make changes to this file in this repo as they will be overwritten with changes made to the same file in above mentioned repo

# Purpose of this workflow is to enable anyone to label PR with the following labels:
# `ready-to-merge` and `do-not-merge` labels to get stuff merged or blocked from merging
# `auto-update` to keep a branch up-to-date with the target branch

name: Add label to PR # if proper comment added

on: 
    issue_comment:
        types: 
            - created

jobs:
  parse-comment-and-add-label:
    if: github.event.issue.pull_request && github.event.issue.state != 'closed' && github.actor != 'asyncapi-bot'
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is draft # such info is not available in the context of issue_comment event
        uses: actions/github-script@v5
        id: checkDraft
        with:
          result-encoding: string
          script: |
            const prDetailsUrl = context.payload.issue.pull_request.url;
            const response = await github.request(prDetailsUrl);
            return response.data.draft;

      - name: Add ready-to-merge label
        if: steps.checkDraft.outputs.result == 'false' && (contains(github.event.comment.body, '/ready-to-merge') || contains(github.event.comment.body, '/rtm' ))
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['ready-to-merge']
            }) 

      - name: Add do-not-merge label
        if: contains(github.event.comment.body, '/do-not-merge') || contains(github.event.comment.body, '/dnm' )
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['do-not-merge']
            }) 

      - name: Add autoupdate label
        if: steps.checkDraft.outputs.result == 'false' && (contains(github.event.comment.body, '/auto-update') || contains(github.event.comment.body, '/au' ))
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['auto-update']
            }) 